#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void int1(int error){printf("interrupt 1 generated by error %d\n", error);}
void int2(int error){printf("Interrupt 2 generated by error %d\n", error);}
void int3(int error){printf("Interrupt 3 generated by error %d\n", error);}
void main(){
	void (*interrupts[])(int error) = {int1, int2, int3};
	int error=0;
	srand(time(NULL));
	while (1){
		error = rand() % 3;
		interrupts[error](error);
		sleep(5);
	}

}
